apiVersion: v1 
kind: Service
metadata:
  name: iweblens-service
spec:
  type: NodePort
  selector:
    app: iweblens
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
